version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
{%- if cookiecutter.pattern in ("js", "jupyter") %}
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"
{%- endif %}
