language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -e .[dev]
    - yarn

script: 
  - make test

# after_success:
#     - codecov --token <token>

branches:
  only:
  - master

notifications:
  email: false
